{{- if .Values.logRetention.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: {{ include "NotifyBC.fullname" . }}-logs
  labels: {{- include "NotifyBC.labels" . | nindent 4}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.logRetention.persistence.size }}
  storageClassName: {{ .Values.logRetention.persistence.storageClassName }}
{{ end }}
