apiVersion: v1
entries:
  notify-bc:
  - apiVersion: v2
    appVersion: "5.2"
    created: "2024-10-30T21:28:27.938551136Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 14.3.2
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.2
    description: NotifyBC Helm chart for Kubernetes
    digest: b07b7e75c2ab657192c19ada0147ae58e478258dd7651e603d1c4b0d82d84925
    icon: https://raw.githubusercontent.com/bcgov/NotifyBC/main/favicon.ico
    name: notify-bc
    type: application
    urls:
    - https://bcgov.github.io/des-notifybc/helm/notify-bc-5.2.0-pr62.tgz
    version: 5.2.0-pr62
  - apiVersion: v2
    appVersion: "5.2"
    created: "2024-10-30T21:32:05.538903468Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 14.13.0
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.2
    description: NotifyBC Helm chart for Kubernetes
    digest: 8344b90afe8a4cc1fd0897c0550efd88687f06d3947c2683d0bdbb21ad32c185
    icon: https://raw.githubusercontent.com/bcgov/NotifyBC/main/favicon.ico
    name: notify-bc
    type: application
    urls:
    - https://bcgov.github.io/des-notifybc/helm/notify-bc-5.2.0-pr53.tgz
    version: 5.2.0-pr53
  - apiVersion: v2
    appVersion: "5.2"
    created: "2024-10-30T21:43:25.068636394Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 14.3.2
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.2
    description: NotifyBC Helm chart for Kubernetes
    digest: f3d6df3bab7672411a6db65938147407580894507620d40829e018ab76f80e4c
    icon: https://raw.githubusercontent.com/bcgov/NotifyBC/main/favicon.ico
    name: notify-bc
    type: application
    urls:
    - https://bcgov.github.io/des-notifybc/helm/notify-bc-5.2.0.tgz
    version: 5.2.0
  - apiVersion: v2
    appVersion: "5.1"
    created: "2024-08-13T22:52:37.872836943Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 14.3.2
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.2
    description: NotifyBC Helm chart for Kubernetes
    digest: c403b522f333d8a9af5b855e9ec919aa424515000fd9fa059ed0e8f462d67179
    icon: https://raw.githubusercontent.com/bcgov/NotifyBC/main/favicon.ico
    name: notify-bc
    type: application
    urls:
    - https://bcgov.github.io/des-notifybc/helm/notify-bc-5.1.4-pr50.tgz
    version: 5.1.4-pr50
  - apiVersion: v2
    appVersion: "5.1"
    created: "2024-10-30T21:31:19.490324518Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 14.3.2
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.2
    description: NotifyBC Helm chart for Kubernetes
    digest: aa754b4d0365c80968b455da35b3885bf467c788d8c99606d2cfac6565eac1f9
    icon: https://raw.githubusercontent.com/bcgov/NotifyBC/main/favicon.ico
    name: notify-bc
    type: application
    urls:
    - https://bcgov.github.io/des-notifybc/helm/notify-bc-5.1.3.tgz
    version: 5.1.3
  - apiVersion: v2
    appVersion: "5.1"
    created: "2024-08-27T21:29:06.230525759Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 14.3.2
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.2
    description: NotifyBC Helm chart for Kubernetes
    digest: b8d0df8c0f800668e6834c47d260c4cb0e9e825766ac51fd5ddcfa7e80f65ec2
    icon: https://raw.githubusercontent.com/bcgov/NotifyBC/main/favicon.ico
    name: notify-bc
    type: application
    urls:
    - https://bcgov.github.io/des-notifybc/helm/notify-bc-5.1.3-pr57.tgz
    version: 5.1.3-pr57
  - apiVersion: v2
    appVersion: "5.1"
    created: "2024-09-13T22:25:58.134276049Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 14.13.0
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.2
    description: NotifyBC Helm chart for Kubernetes
    digest: ff65234861615c4169f8a26e46d63ee72661818c3585fc4e8d880941d483dd88
    icon: https://raw.githubusercontent.com/bcgov/NotifyBC/main/favicon.ico
    name: notify-bc
    type: application
    urls:
    - https://bcgov.github.io/des-notifybc/helm/notify-bc-5.1.3-pr53.tgz
    version: 5.1.3-pr53
  - apiVersion: v2
    appVersion: "5.1"
    created: "2024-08-02T21:49:27.900226202Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 14.3.2
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.2
    description: NotifyBC Helm chart for Kubernetes
    digest: e0e3e0eed3cd95d1631066df717f932b159059e5d888de3a3641688b3f410ea8
    icon: https://raw.githubusercontent.com/bcgov/NotifyBC/main/favicon.ico
    name: notify-bc
    type: application
    urls:
    - https://bcgov.github.io/des-notifybc/helm/notify-bc-5.1.3-pr48.tgz
    version: 5.1.3-pr48
  - apiVersion: v2
    appVersion: "5.1"
    created: "2024-07-30T15:25:11.928413121Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 14.3.2
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.2
    description: NotifyBC Helm chart for Kubernetes
    digest: b85f7b41011e4ebe8cf8fbc3c9f74fa7d51e35199e8b4ba17b0470d6f4446fbc
    icon: https://raw.githubusercontent.com/bcgov/NotifyBC/main/favicon.ico
    name: notify-bc
    type: application
    urls:
    - https://bcgov.github.io/des-notifybc/helm/notify-bc-5.1.3-pr45.tgz
    version: 5.1.3-pr45
  - apiVersion: v2
    appVersion: "5.1"
    created: "2024-08-01T17:21:03.44699293Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 14.3.2
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.2
    description: NotifyBC Helm chart for Kubernetes
    digest: 435e0260614c07db2476c20c99c92bffb6feab1664c03a137b2e1f89763262d8
    icon: https://raw.githubusercontent.com/bcgov/NotifyBC/main/favicon.ico
    name: notify-bc
    type: application
    urls:
    - https://bcgov.github.io/des-notifybc/helm/notify-bc-5.1.3-pr44.tgz
    version: 5.1.3-pr44
  - apiVersion: v2
    appVersion: "5.1"
    created: "2024-07-23T18:22:11.8288415Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 14.3.2
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.2
    description: NotifyBC Helm chart for Kubernetes
    digest: 5d88e562bdcacb58d2d18825f62aa7fb6bf1d8bb44cd196af108d3cd5df8fd37
    icon: https://raw.githubusercontent.com/bcgov/NotifyBC/main/favicon.ico
    name: notify-bc
    type: application
    urls:
    - https://bcgov.github.io/des-notifybc/helm/notify-bc-5.1.3-pr43.tgz
    version: 5.1.3-pr43
  - apiVersion: v2
    appVersion: "5.1"
    created: "2024-07-16T16:53:01.328406716Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 14.3.2
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.2
    description: NotifyBC Helm chart for Kubernetes
    digest: cd7edc71136f8dc99430edbd40cd823c5c3b4c9c6ca64b0298746fe155b60331
    icon: https://raw.githubusercontent.com/bcgov/NotifyBC/main/favicon.ico
    name: notify-bc
    type: application
    urls:
    - https://bcgov.github.io/des-notifybc/helm/notify-bc-5.1.3-pr42.tgz
    version: 5.1.3-pr42
  - apiVersion: v2
    appVersion: "5.1"
    created: "2024-07-12T17:31:34.420227283Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 14.3.2
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.2
    description: NotifyBC Helm chart for Kubernetes
    digest: 1d5a692745d04214011672655560dc7e3655398065cd90e282c59eec9d1be323
    icon: https://raw.githubusercontent.com/bcgov/NotifyBC/main/favicon.ico
    name: notify-bc
    type: application
    urls:
    - https://bcgov.github.io/des-notifybc/helm/notify-bc-5.1.3-pr41.tgz
    version: 5.1.3-pr41
  - apiVersion: v2
    appVersion: "5.1"
    created: "2024-07-09T22:38:00.586789Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 14.3.2
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.2
    description: NotifyBC Helm chart for Kubernetes
    digest: 0a3c3481d783d50906190ebd54c7aab0bc1dc68ada13720ce3cf519e51051ab9
    icon: https://raw.githubusercontent.com/bcgov/NotifyBC/main/favicon.ico
    name: notify-bc
    type: application
    urls:
    - https://bcgov.github.io/des-notifybc/helm/notify-bc-5.1.3-pr40.tgz
    version: 5.1.3-pr40
  - apiVersion: v2
    appVersion: "5.1"
    created: "2024-06-19T16:44:46.345869-07:00"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 14.3.2
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.2
    description: NotifyBC Helm chart for Kubernetes
    digest: f234602e8f133edd7402b159744ab4b02aa3129a947979a12ed76c47c5ae0428
    icon: https://raw.githubusercontent.com/bcgov/NotifyBC/main/favicon.ico
    name: notify-bc
    type: application
    urls:
    - https://bcgov.github.io/des-notifybc/helm/notify-bc-5.1.2.tgz
    version: 5.1.2
  - apiVersion: v2
    appVersion: "5.1"
    created: "2024-06-20T17:33:10.326308844Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 14.3.2
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.2
    description: NotifyBC Helm chart for Kubernetes
    digest: 967662c079e7eeb886d3d8f761a1b8807da39b23685a09fc3714ed297a8b64ba
    icon: https://raw.githubusercontent.com/bcgov/NotifyBC/main/favicon.ico
    name: notify-bc
    type: application
    urls:
    - https://bcgov.github.io/des-notifybc/helm/notify-bc-5.1.2-test.tgz
    version: 5.1.2-test
  - apiVersion: v2
    appVersion: "5.1"
    created: "2024-07-15T21:04:43.663450547Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 14.3.2
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.2
    description: NotifyBC Helm chart for Kubernetes
    digest: b3a88a2be1f61adea9fa8ffdfb7327b8e2aafa14a0382c0ed643c99059054a15
    icon: https://raw.githubusercontent.com/bcgov/NotifyBC/main/favicon.ico
    name: notify-bc
    type: application
    urls:
    - https://bcgov.github.io/des-notifybc/helm/notify-bc-5.1.2-pr42.tgz
    version: 5.1.2-pr42
  - apiVersion: v2
    appVersion: "5.1"
    created: "2024-06-20T21:18:31.356022Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 14.3.2
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.2
    description: NotifyBC Helm chart for Kubernetes
    digest: d590db653fa6432b05630be8cc349d35704c610d0dce74d0c4e4a516219a8b44
    icon: https://raw.githubusercontent.com/bcgov/NotifyBC/main/favicon.ico
    name: notify-bc
    type: application
    urls:
    - https://bcgov.github.io/des-notifybc/helm/notify-bc-5.1.2-pr36.tgz
    version: 5.1.2-pr36
  - apiVersion: v2
    appVersion: "5.1"
    created: "2024-07-17T11:55:03.621627-07:00"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 14.3.2
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.2
    description: NotifyBC Helm chart for Kubernetes
    digest: b9126cbd764bba6a432240f400d4dc4c59a2f839f3a15689e92a44117027970b
    icon: https://raw.githubusercontent.com/bcgov/NotifyBC/main/favicon.ico
    name: notify-bc
    type: application
    urls:
    - https://bcgov.github.io/des-notifybc/helm/notify-bc-5.1.2-alpha.tgz
    version: 5.1.2-alpha
  - apiVersion: v2
    appVersion: "4.1"
    created: "2024-06-19T16:44:46.306102-07:00"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 14.3.2
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.2
    description: NotifyBC Helm chart for Kubernetes
    digest: b32ea5bbea5f52b1507f720ed595d06703a998e4b37d0acf8688b6c63e5f8b33
    icon: https://raw.githubusercontent.com/bcgov/NotifyBC/main/favicon.ico
    name: notify-bc
    type: application
    urls:
    - https://bcgov.github.io/des-notifybc/helm/notify-bc-4.1.11.tgz
    version: 4.1.11
  - apiVersion: v2
    appVersion: "4.1"
    created: "2024-06-19T16:44:46.332997-07:00"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 14.3.2
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.2
    description: NotifyBC Helm chart for Kubernetes
    digest: a377c14d11a3a7f95e930e1773c623dabe7c1b5ceefc17f62dcc0e4ef1a2553c
    icon: https://raw.githubusercontent.com/bcgov/NotifyBC/main/favicon.ico
    name: notify-bc
    type: application
    urls:
    - https://bcgov.github.io/des-notifybc/helm/notify-bc-4.1.3.tgz
    version: 4.1.3
  - apiVersion: v2
    appVersion: "4.1"
    created: "2024-06-19T16:44:46.320559-07:00"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 14.3.2
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.2
    description: NotifyBC Helm chart for Kubernetes
    digest: cdae314a743a3ef0eb7a9a608eb525df4beabce31bfa523e2a46661f008e16a0
    icon: https://raw.githubusercontent.com/bcgov/NotifyBC/main/favicon.ico
    name: notify-bc
    type: application
    urls:
    - https://bcgov.github.io/des-notifybc/helm/notify-bc-4.1.2.tgz
    version: 4.1.2
  - apiVersion: v2
    appVersion: "4.1"
    created: "2024-06-19T16:44:46.293757-07:00"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 14.3.2
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.2
    description: NotifyBC Helm chart for Kubernetes
    digest: b5ed40035d2dfb7d56e9430dd4763e9352d0e23b20f2cec2bc4ceb72a4a35f8c
    icon: https://raw.githubusercontent.com/bcgov/NotifyBC/main/favicon.ico
    name: notify-bc
    type: application
    urls:
    - https://bcgov.github.io/des-notifybc/helm/notify-bc-4.1.1.tgz
    version: 4.1.1
  - apiVersion: v2
    appVersion: "4.1"
    created: "2024-06-19T16:44:46.275905-07:00"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 14.3.2
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.2
    description: NotifyBC Helm chart for Kubernetes
    digest: 4e9864a0a3d3b95ec87fae6fd57434e10ee10cc178a6325f1e3d6c1f68f5a2af
    icon: https://raw.githubusercontent.com/bcgov/NotifyBC/main/favicon.ico
    name: notify-bc
    type: application
    urls:
    - https://bcgov.github.io/des-notifybc/helm/notify-bc-4.1.0.tgz
    version: 4.1.0
  - apiVersion: v2
    appVersion: "5.0"
    created: "2024-06-19T16:44:46.266743-07:00"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 14.3.2
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.2
    description: NotifyBC Helm chart for Kubernetes
    digest: fb1d2c8e262bfd8357d43c262c488ae835044d91a852282b6b7be153663f620d
    icon: https://raw.githubusercontent.com/bcgov/NotifyBC/main/favicon.ico
    name: notify-bc
    type: application
    urls:
    - https://bcgov.github.io/des-notifybc/helm/notify-bc-2.0.0.tgz
    version: 2.0.0
generated: "2024-10-30T21:43:25.057002189Z"
